name: Create Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  create-release:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
      version: ${{ steps.get_version.outputs.version }}

    steps:
      - uses: actions/checkout@v3

      - name: Get version
        id: get_version
        run: echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          body: |
            ## YarrHarr ${{ github.ref_name }}

            ### Changes in this version:
            - Please check the [CHANGELOG.md](CHANGELOG.md) for details

            ### Downloads
            - Automated builds will be attached to this release

            ### Installation
            Please see the [README.md](README.md) for installation instructions.

  build:
    needs: create-release
    uses: ./.github/workflows/build.yml
    with:
      upload_url: ${{ needs.create-release.outputs.upload_url }}
    secrets: inherit

  update-homebrew:
    needs: [create-release, build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout homebrew-tap
        uses: actions/checkout@v3
        with:
          repository: asleepynerd/homebrew-tap
          token: ${{ secrets.TAP_TOKEN }}  # You'll need to create this

      - name: Calculate SHA256
        run: |
          curl -L https://github.com/asleepynerd/yarrharr/archive/refs/tags/v${{ needs.create-release.outputs.version }}.tar.gz | sha256sum | cut -d' ' -f1 > sha.txt

      - name: Update Formula
        run: |
          SHA=$(cat sha.txt)
          VERSION=${{ needs.create-release.outputs.version }}
          sed -i "s/version .*/version \"${VERSION}\"/" Formula/yarrharr.rb
          sed -i "s/sha256 .*/sha256 \"${SHA}\"/" Formula/yarrharr.rb

      - name: Commit and Push
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add Formula/yarrharr.rb
          git commit -m "yarrharr ${{ needs.create-release.outputs.version }}"
          git push
